# -*- coding: utf-8 -*-
"""Ciencia de Datos: Dataframe ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DS_r5hLmCT8NN2cqcJCIBxRzNd6mx1UR

#Dataframes
1. Columnas (Features - caracteristicas)
2. Filas (Registros)

Siempre se deben importar las librerias de Numpy y pandas
"""

import numpy as np
import pandas as pd

#Convertir de listas a dataframe
Ventas=pd.Series([22,15,71])
Ventas

ventas=pd.Series([22,15,71],index=['Enero','Febrero','Marzo'])
ventas

ventas["Enero"]

ventas.dtype

#Para visualizar features
ventas.index

#Para obtener los valores de la feature
ventas.values

ventas.name="Ventas del 2025"
ventas

#Para nombrar el index
ventas.index.name="Meses"
ventas

ventas.shape

"""1. Los diccionarios tienen una clave unica, y un valor asociado a la clave (string)
2. No se pueden indezar (No se sabe la pocision de datos)
3. Son mutables
"""

diccionario={"Enero":22,"Febrero":15,"Marzo":71}
type(diccionario)

#Convertir diccionario a dataframe
ventas1=pd.Series(diccionario)
ventas1

alex=pd.Series(diccionario,index=["Enero","Febrero","Marzo","Abril"])
alex

medidas=pd.DataFrame(
    {"Humedad":[41,20,30,80],
     "Salinidad":[22,15,30,80],
     "Sensórica":["Sí","No","No","No"],
     "Acidez":["alta","media","baja","baja"],
     "ph":[1,7,14,13]},
    index=["La Ureña","Paso Chino","La Laguna","Los Teres"],
)

medidas

medidas.index.name="Meses"
medidas

medidas[["ph","Humedad"]]

#Nombres Filas y columnas
medidas.axes

medidas.shape



"""###Ejercicios
Dados los siguientes diccionarios, convertirlos en datagramas y usar todos los métodos aprendidos:

```
elementos={"número atómico":[1,6,47,88],
"Masa atómica":[1,12,107,226],
"Familia":["No metal","No metal","Metal","Metal"]}
```
Agregar como registros el nombre de los elementos

2. Convertir en dataframe el siguiente conjunto de medidas
```
medida_2020={"Ag":2,"Au":5,"Cu":3,"Pt:2}
medida_2021={"Ag":4,"Au":3,"Cu":6,"Pt:1}
medida_2022={"Ag":8,"Au":2,"Cu":15,"Pt:0}
medida_2023={"Ag":5,"Au":1,"Cu":0,"Pt:5}
medida_2024={"Ag":7,"Au":0,"Cu":3,"Pt:2}
medida_20205={"Ag":9,"Au":1,"Cu":3,"Pt:5}
```
Tenga en cuenta que los registros son los meses de medida y las features deben ser los elementos
"""

elementos=pd.DataFrame(
    {"Número atómico":[1,6,47,88],
    "Masa atómica":[1,12,107,226],
    "Familia":["No metal","No metal","Metal","Metal"]},
    index=["Hidrogeno","Carbono","Plata","Radio"])

elementos

elementos.index.name="Elementos"
elementos

elementos.index

elementos.dtypes

elementos.axes

elementos.values

elementos[["Familia","Número atómico"]]

elementos.shape

medidas=pd.DataFrame(
    {"2020":{"Ag":2,"Au":5,"Cu":3,"Pt":2},
    "2021":{"Ag":4,"Au":3,"Cu":6,"Pt":1},
    "2022":{"Ag":8,"Au":2,"Cu":15,"Pt":0},
    "2023":{"Ag":5,"Au":1,"Cu":0,"Pt":5},
    "2024":{"Ag":7,"Au":0,"Cu":3,"Pt":2},
    "2025":{"Ag":9,"Au":1,"Cu":3,"Pt":5}})
medidas

medidas.index.name="Elementos"
medidas

medidas.dtypes

medidas.axes

medidas.values

medidas.shape

medidas[["2023","2021"]]