# -*- coding: utf-8 -*-
"""Tarea Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAuWjZzu4kMnMST4hOnAzOJq1N_dPQTp
"""

import pandas as pd
df= pd.read_excel("titanic3.xls")
df

df.index.name = "Datos"

df.columns

df.name

df.dtypes

df.axes

df.shape

df[['name', 'sex', 'age']]